DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE

SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    PRINT CONVERT(VARCHAR(10), @DATAINICIAL) 
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END